"""
Train a RF model on the dataset(s) generated by dnabert/inference/inference.py
    - Should be located at ../dnabert/inference/outputs/rf_datasets/{MODEL_NAME}/{grouping}/{train} by default
    - Trains RF model on DEV portion of TRAIN set 
        - This is because DNABERT was trained on train portion, so we cant use this poriton for training RF

If --eval is true, will evaluate models on TEST PORTION OF TRAIN SET, not independent validation test set from CAMDA site
"""


# lists/mappings
species_list = [
    'neisseria_gonorrhoeae', 
    'staphylococcus_aureus', 
    'streptococcus_pneumoniae', 
    'salmonella_enterica', 
    'klebsiella_pneumoniae', 
    'escherichia_coli', 
    'pseudomonas_aeruginosa', 
    'acinetobacter_baumannii', 
    'campylobacter_jejuni' 
]

antibiotic_to_species ={
    'GEN': ['klebsiella_pneumoniae', 'escherichia_coli', 'salmonella_enterica'],
    'ERY': ['streptococcus_pneumoniae', 'staphylococcus_aureus'],
    'CAZ': ['pseudomonas_aeruginosa', 'acinetobacter_baumannii'],
    'TET': ['neisseria_gonorrhoeae', 'campylobacter_jejuni'],
}


# imports
import argparse
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import joblib
import os
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import json
from tqdm import tqdm
import numpy as np
import csv
import io
from contextlib import redirect_stdout
import matplotlib.pyplot as plt
import glob
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
import torch

# methods

def preprocess_df(df, species, args, importances=None):
    """ Preprocess dataset for training """

    def filter_feature_type(X, feature_type, top_n_mi_score=None):
        """ Remove hit_count or pred_resistant columns based on feature_type,
        as well as other unnecessary columns like accession, species, antibiotic, ground_truth_phenotype,
        to be used for X dataset (features) """

        X = X.drop(['accession', 'species', 'antibiotic'], axis=1) # we dont need species and antibiotic if were doing per-species models (all the same)
        extra_cols_to_keep = ['ground_truth_phenotype']#['random']

        if feature_type == 'dnabert':
            cols_to_keep = [col for col in X.columns if 'pred_resistant' in col]
            cols_to_keep.extend(extra_cols_to_keep)
            X = X[cols_to_keep]
        elif feature_type == 'hits':
            cols_to_keep = [col for col in X.columns if 'hit_count' in col]
            cols_to_keep.extend(extra_cols_to_keep)
            X = X[cols_to_keep]
        elif feature_type == 'both':
            return X
        else:
            raise ValueError(f"Invalid feature type: {feature_type}")

        return X

    def filter_accs(df, species, args):
        """ Remove accessions from dataset based on accs_to_skip """
        if args.skip_accs is None:
            return df
        accs_to_skip = set([line.strip() for line in open(os.path.join(args.skip_accs, f'{species}.txt'))])
        return df[~df['accession'].isin(accs_to_skip)]

    def flip_phenotype(df, species, args):
        if args.flip_phenotype is None:
            return df
        accs_to_flip = set([line.strip() for line in open(os.path.join(args.flip_phenotype, f'{species}.txt'))])
        df.loc[df['accession'].isin(accs_to_flip), 'ground_truth_phenotype'] = df.loc[df['accession'].isin(accs_to_flip), 'ground_truth_phenotype'].map({1: 0, 0: 1})
        return df

    def feature_selection(num_features, df, species, args, importances):
        """
        Select top num_features most important features from the dataframe.
        
        Args:
            num_features: Number of top features to keep
            df: Input dataframe containing features and metadata
            
        Returns:
            DataFrame with only the selected features and required metadata columns
        """
        # Load feature importances if not already loaded
        
        
        if species not in importances:
            raise ValueError(f"No feature importances found for species: {species}")
        
        # Get the top N features for this species
        available = importances[species]
        if len(available) == 0:
            raise ValueError(f"No features recorded for species {species} under current feature_type. Check that the pretrained models include matching feature names.")

        # use as many as are available (could be less than requested)
        selected_features = available[:min(num_features, len(available))]
        
        # Identify metadata columns that should always be kept
        metadata_columns = ['accession', 'species', 'antibiotic', 'random', 'ground_truth_phenotype']
        metadata_columns = [col for col in metadata_columns if col in df.columns]
        
        # Select only the important features + metadata columns
        columns_to_keep = list(set(selected_features + metadata_columns))
        
        return df[columns_to_keep]

    def filter_top_15pct(df, species, args):
        """Filters DNABERT features to only include those in args.top_15pct_features/{species}_top_15%_features.txt"""
        #print(args.top_15pct_features)
        if args.top_15pct_features is None or args.feature_type == 'per_species':
            return df
        path_to_load = os.path.join(args.top_15pct_features, f'{species}_top_15%_features.txt')
        with open(path_to_load, 'r') as f:
            features_to_keep = [line.strip() for line in f]
        dna_features_to_keep = [f.replace('_hit_count', '_pred_resistant') for f in features_to_keep] #since we got these from a hits only RF, we need to change the names of the features
        #handle new feature names:
        dna_features_to_keep = dna_features_to_keep + [f.replace('_hit_count', '_sus_sum_pred_resistant') for f in features_to_keep] + \
        [f.replace('_hit_count', '_sus_mean_pred_resistant') for f in features_to_keep] + [f.replace('_hit_count', '_sus_std_pred_resistant') for f in features_to_keep] + \
        [f.replace('_hit_count', '_res_sum_pred_resistant') for f in features_to_keep] + [f.replace('_hit_count', '_res_mean_pred_resistant') for f in features_to_keep] + \
        [f.replace('_hit_count', '_res_std_pred_resistant') for f in features_to_keep]

        #print(f'length of dna_features_to_keep: {len(dna_features_to_keep)}')
        dna_features_to_keep = [f for f in dna_features_to_keep if f in df.columns]
        #print(f'length of dna_features_to_keep after filtering: {len(dna_features_to_keep)}')
        #remove only pred_resistant columns that are not in features_to_keep, while keeping all other columns
        other_cols_to_keep = [col for col in df.columns if '_pred_resistant' not in col]
        df = df[other_cols_to_keep + dna_features_to_keep]
        return df

    

    def prepare_query_tensor(df):
        import torch
        """
        Reorders dataframe columns so each query_id's 7 features are grouped together.
        Returns a NumPy array ready for model input.
        """
        try:
            phenotype = df['ground_truth_phenotype']
        except ValueError:
            print('No ground_truth_phenotype in df!')
            phenotype=None
        # Extract all unique query IDs from column names
        query_ids = sorted(list(set([c.replace('_hit_count', '') for c in df.columns if '_hit_count' in c])))

        # Define the expected order of feature suffixes
        suffix_order = [
            '_hit_count',
            '_sus_sum_pred_resistant',
            '_sus_mean_pred_resistant',
            '_sus_std_pred_resistant',
            '_res_sum_pred_resistant',
            '_res_mean_pred_resistant',
            '_res_std_pred_resistant'
        ]

        # Build ordered column list
        ordered_cols = []
        for qid in query_ids:
            for suffix in suffix_order:
                col_name = f"{qid}{suffix}"
                if col_name in df.columns:
                    ordered_cols.append(col_name)
                else:
                    # Handle missing columns safely (fill with zeros later)
                    print(f"Warning: Missing {col_name}, will fill with zeros.")
                    df[col_name] = 0
                    ordered_cols.append(col_name)

        # Create reordered DataFrame
        df_ordered = df[ordered_cols]
        if phenotype is not None:
            df_ordered['ground_truth_phenotype'] = phenotype

        #X_array = df_ordered.to_numpy(dtype=np.float32)

        return df_ordered
    



    df = filter_accs(df, species, args)
    df = flip_phenotype(df, species, args)
    #print(species)
    df = filter_feature_type(df, args.feature_type)
    #print(f'before top15pct: {df.shape}')
    if args.top_15pct_features is not None:
        df = filter_top_15pct(df, species, args)
    #print(f'after top15pct: {df.shape}')
    if args.feature_plot is not None:
        df = feature_selection(num_features=args.num_features, df=df, species=species, args=args, importances=importances)
    #print(f'after feature selection: {df.shape}')
    #print()

    #print(f'NaNs in dataset: {df.isna().sum()}')

    df = df.fillna(0)

    #scale logits with standardscaler
    if args.scaler == 'standard':
        num_features = [c for c in df.columns if '_pred_resistant' in c]
        low_card = [c for c in df.columns if '_hit_count' in c]
        if not os.path.exists(os.path.join(args.out_dir, species+'_stdscaler.pkl')):
            print('No scaler found, fitting new one...')
            scaler = ColumnTransformer([
                ('num', StandardScaler(), num_features),
                ('lowcard', 'passthrough', low_card)
            ])
            joblib.dump(scaler, os.path.join(args.out_dir, species+'_stdscaler.pkl'))
        else:
            print('Loading scaler...')
            scaler = joblib.load(os.path.join(args.out_dir, species+'_stdscaler.pkl'))

        scaled_array = scaler.fit_transform(df)
        scaled_df = pd.DataFrame(scaled_array, columns=num_features + low_card, index=df.index)
        scaled_columns = num_features + low_card  # order matches transformer definition
        assert len(scaled_columns) == len(set(scaled_columns)), "Duplicate columns found!"

        scaled_df['ground_truth_phenotype'] = df['ground_truth_phenotype']
        print(df.columns)
        df = scaled_df

    if args.model_type=='nn':
        df = prepare_query_tensor(df)


    return df


    





"""def filter_top_n_mi(X, species, models_dir, y=None, top_n_mi_score=None):
    if top_n_mi_score is None:
        return X
    else:
        extra_cols_to_keep = []#['random']
        if y is not None:
            from sklearn.feature_selection import mutual_info_classif
            mi_scores = mutual_info_classif(X, y, discrete_features='auto')
            mi_df = pd.DataFrame({
                "feature": X.columns,
                "mi_score": mi_scores
            }).sort_values(by="mi_score", ascending=False)

            features_to_keep = list(mi_df.head(top_n_mi_score).feature)
            features_to_keep.extend(extra_cols_to_keep)
            X = X[features_to_keep]
            #save features so we can load them during inference
            os.makedirs(os.path.join(models_dir, 'mi_features'), exist_ok=True)
            path_to_save = os.path.join(models_dir, 'mi_features', f'{species}_mi_features.txt')
            with open(path_to_save, 'w') as f:
                for feature in features_to_keep:
                    f.write(f"{feature}\n")
        else: #if we dont pass y (during inference), we must have already saved features during training
            #load features
            path_to_load = os.path.join(models_dir, 'mi_features', f'{species}_mi_features.txt')
            with open(path_to_load, 'r') as f:
                features_to_keep = [line.strip() for line in f]
            features_to_keep.extend(extra_cols_to_keep)
            X = X[features_to_keep]
        
        return X"""

def feature_plot(args):
    """
    Plot model performance vs number of features used.
    For each feature type in ['dnabert', 'hits', 'both']:
      - Build species-wise feature order from pretrained models using feature_names_in_ and feature_importances_
        (filtered to the feature type rules)
      - Sweep number of features: 1, 20, 40, ..., 2000
      - Train and evaluate models at each sweep point (using the filtered features)
      - Save per-species accuracies JSON and plots (per-species curves and averaged curve)
      - Print and save top-5 features per species
    Finally, create a combined averaged-curve plot across the three feature types.
    """
    # Ensure output directories exist
    os.makedirs('eval_results/figures', exist_ok=True)
    os.makedirs('eval_results', exist_ok=True)

    # Directory containing pretrained models (hits-only if interleave, otherwise whatever user supplied)
    models_dir = args.feature_plot

    # Build base hits importance order per species (always needed)
    base_hits_importances = {}
    for species in species_list:
        model_path = os.path.join(models_dir, f"{species}_{args.model_type}_model.joblib")
        if not os.path.exists(model_path):
            raise FileNotFoundError(f"Pretrained model not found: {model_path}")
        model = joblib.load(model_path)
        importances = model.feature_importances_
        feature_names = list(model.feature_names_in_)
        indices = np.argsort(importances)[::-1]
        ordered_hits = [feature_names[i] for i in indices]
        base_hits_importances[species] = ordered_hits

    # Number of features sweep (1‒1500)
    num_features_list = list(range(1, 200, 1))

    combined_avg = {}
    prev_feature_type = args.feature_type
    try:
        for ft in ['hits', 'dnabert', 'both']:
            args.feature_type = ft
            print(args.feature_type)

            # Construct feature_importances according to ft and interleave logic
            feature_importances = {}
            for species, hits_list in base_hits_importances.items():
                if ft == 'hits':
                    final_order = [h for h in hits_list if 'hit_count' in h]
                elif ft == 'dnabert':
                    final_order = [h for h in hits_list if 'pred_resistant' in h]
                elif ft == 'both':
                    if args.interleave:
                        raise NotImplementedError('Interleave not implemented')
                    else:
                        final_order = hits_list
                else:
                    raise ValueError
                feature_importances[species] = final_order

            # Persist the current feature_importances so feature_selection() can use them during train/eval
            with open('eval_results/feature_importances.json', 'w') as f:
                json.dump(feature_importances, f)

            # Sweep and collect accuracies per species
            species_accuracies = {species: [] for species in species_list}
            for num_features in tqdm(num_features_list, desc=f"Evaluating feature type={ft}"):
                args.num_features = num_features
                if ft == 'both' and args.oof_stack:
                    oof_train(args, feature_importances)
                    eval_results = eval_oof(args, feature_importances)
                else:  
                    train(args, feature_importances)
                    eval_results = eval(args, feature_importances)

                for species in species_list:
                    species_accuracies[species].append(eval_results['accuracy'][species])

            # Save accuracies used for plotting
            with open(f'eval_results/feature_plot_accuracies_{ft}.json', 'w') as f:
                json.dump({
                    'num_features_list': num_features_list,
                    'accuracies': species_accuracies
                }, f)

            # Plot per-species curves
            plt.figure(figsize=(12, 8))
            for species in species_list:
                plt.plot(num_features_list, species_accuracies[species], label=species)
            plt.xlabel('Number of Features Kept')
            plt.ylabel('Accuracy')
            plt.title(f'Per-Species Accuracy vs Number of Features ({ft})')
            plt.legend()
            plt.grid(True)
            per_species_plot_path = f'eval_results/figures/{args.model_name}/feature_plot_{ft}.png'
            os.makedirs(os.path.dirname(per_species_plot_path), exist_ok=True)
            plt.savefig(per_species_plot_path, bbox_inches='tight')
            plt.close()
            print(f"Per-species feature plot saved to {per_species_plot_path}")

            # Averaged curve plot for this feature type
            avg_accuracies = [
                float(np.mean([species_accuracies[s][i] for s in species_list]))
                for i in range(len(num_features_list))
            ]
            combined_avg[ft] = avg_accuracies

            plt.figure(figsize=(12, 8))
            plt.plot(num_features_list, avg_accuracies, marker='o')
            plt.xlabel('Number of Features Kept')
            plt.ylabel('Average Accuracy (across species)')
            plt.title(f'Average Accuracy vs Number of Features ({ft})')
            plt.grid(True)
            avg_plot_path = f'eval_results/figures/{args.model_name}/feature_plot_avg_{ft}.png'
            os.makedirs(os.path.dirname(avg_plot_path), exist_ok=True)
            plt.savefig(avg_plot_path, bbox_inches='tight')
            plt.close()
            print(f"Average feature plot saved to {avg_plot_path}")

            # Print and save top-5 features per species for this feature type
            top5 = {sp: feature_importances[sp][:5] for sp in species_list}
            print(f"Top-5 features per species (by RF importance) for feature_type={ft}:")
            for sp, feats in top5.items():
                print(f"  {sp}: {feats}")
            with open(f'eval_results/top5_features_{ft}.json', 'w') as f:
                json.dump(top5, f)

        # Combined plot: averaged accuracies vs num features for each feature type
        plt.figure(figsize=(12, 8))
        for ft in ['dnabert', 'hits', 'both']:
            if ft in combined_avg:
                plt.plot(num_features_list, combined_avg[ft], label=ft)
        plt.xlabel('Number of Features Kept')
        plt.ylabel('Average Accuracy (across species)')
        plt.title('Average Accuracy vs Number of Features by Feature Type')
        plt.legend(title='Feature Type')
        plt.grid(True)
        combined_plot_path = f'eval_results/figures/{args.model_name}/feature_plot_avg_by_feature_type.png'
        os.makedirs(os.path.dirname(combined_plot_path), exist_ok=True)
        plt.savefig(combined_plot_path, bbox_inches='tight')
        plt.close()
        print(f"Combined average feature plot saved to {combined_plot_path}")

        #place args.json to eval_results
        
        with open(os.path.dirname(combined_plot_path) + '/args.json', 'w') as f:
            json.dump(args.__dict__, f)

    finally:
        # Restore the original feature_type
        args.feature_type = prev_feature_type


def oof_train(args, importances=None):
    """3-fold out-of-fold stacking with hits & DNABERT base models"""
    
    original_train_on = args.train_on
    if importances is not None:
        original_feature_importances = importances.copy()

    base_out_dir = os.path.join(args.base_dir, 'rf', 'models', 'oof', args.model_name)
    folds = sorted([d.split('_')[-1] for d in os.listdir(args.dataset_dir)])
    folds = ['fold_'+f for f in folds]
    assert len(folds) == 3, 'Expect dataset_dir to contain fold_0 fold_1 fold_2'

    oof_preds_hits = {sp: [] for sp in species_list}
    oof_preds_hits ={fold: oof_preds_hits for fold in folds}
    oof_preds_dna  = {sp: [] for sp in species_list}
    oof_preds_dna ={fold: oof_preds_dna for fold in folds}
    oof_truth      = {sp: [] for sp in species_list}
    oof_truth ={fold: oof_truth for fold in folds}

    for held_out in folds:
        train_on = ''.join(sorted([f[-1] for f in folds if f != held_out]))  # e.g. '01'
        for dirname in os.listdir(args.dataset_dir):
            #print(dirname)
            if held_out in str(dirname):
                held_path = os.path.join(args.dataset_dir, dirname)
        print(f"\n### OOF loop – hold {held_out}, train_on={train_on} ###")

        for ft in ['hits', 'dnabert']:
            args.feature_type = ft
            args.train_on = train_on
            args.out_dir = os.path.join(base_out_dir, ft, f"exclude_{held_out}")
            os.makedirs(args.out_dir, exist_ok=True)
            feature_importances = {}
    
            if importances is not None:
                
                for sp in species_list:
                    if ft == 'hits':
                        feature_importances[sp] = [f for f in original_feature_importances[sp] if '_hit_count' in f]
                    else:
                        feature_importances[sp] = [f for f in original_feature_importances[sp] if '_pred_resistant' in f]
            else:
                feature_importances=None

            train(args, feature_importances)

            # inference on held_out fold
            for sp in species_list:
                model = joblib.load(os.path.join(args.out_dir, f"{sp}_{args.model_type}_model.joblib"))
                df = pd.read_csv(os.path.join(held_path, args.dnabert_grouping, 'train', sp, f"{sp}_full_rf_dataset.csv"))
                df = preprocess_df(df, sp, args)
                X_inf = df.drop('ground_truth_phenotype', axis=1)
                
                proba = model.predict_proba(X_inf)[:,1].tolist()
                if ft == 'hits':
                    oof_preds_hits[held_out][sp].extend(proba)
                else:
                    oof_preds_dna[held_out][sp].extend(proba)
                if ft == 'hits':  # capture truth once per loop
                    oof_truth[held_out][sp].extend(df['ground_truth_phenotype'].tolist())

    # ---- train meta learner per species ----
    stack_dir = os.path.join(base_out_dir, 'stacker')
    os.makedirs(stack_dir, exist_ok=True)
    for sp in species_list:
        if args.original_train_on!= 'all':

            exclude_fold = {'01':'2', '02':'1', '12':'0'}[args.original_train_on]
            fold_names = []
            for dirname in os.listdir(args.dataset_dir):
                fold=dirname.split('_')[-1]
                if fold == exclude_fold:
                    print(f"Skipping fold {dirname} in meta learner training")
                else:
                    fold_names.append('fold_'+fold)
            
            # train meta learner on fold_0 and fold_1 for evaluation on fold_2 (eval_oof)
            sp_pred_hits = np.concatenate([oof_preds_hits[fold_names[0]][sp], oof_preds_hits[fold_names[1]][sp]], axis=0)
            sp_pred_dna = np.concatenate([oof_preds_dna[fold_names[0]][sp], oof_preds_dna[fold_names[1]][sp]], axis=0)
            sp_truth = np.concatenate([oof_truth[fold_names[0]][sp], oof_truth[fold_names[1]][sp]], axis=0)
        elif args.original_train_on == 'all':
            # train meta learner on all folds for final evaluation (dont run eval_oof)
            sp_pred_hits = np.concatenate([oof_preds_hits['fold_0'][sp], oof_preds_hits['fold_1'][sp], oof_preds_hits['fold_2'][sp]], axis=0)
            sp_pred_dna = np.concatenate([oof_preds_dna['fold_0'][sp], oof_preds_dna['fold_1'][sp], oof_preds_dna['fold_2'][sp]], axis=0)
            sp_truth = np.concatenate([oof_truth['fold_0'][sp], oof_truth['fold_1'][sp], oof_truth['fold_2'][sp]], axis=0)
        
        X_meta = np.column_stack([sp_pred_hits, sp_pred_dna])
        y_meta = np.array(sp_truth)
        meta = LogisticRegression(max_iter=1000)
        meta.fit(X_meta, y_meta)
        print(os.path.join(stack_dir, f"{sp}_stacker.joblib"))
        joblib.dump(meta, os.path.join(stack_dir, f"{sp}_stacker.joblib"))
        acc = accuracy_score(y_meta, meta.predict(X_meta))
        print(f"Stacker saved for {sp}, OOF-train accuracy={acc:.3f}")


def eval_oof(args, importances=None):
    """Evaluate stacker on specified hold out set (in args.original_train_on)"""
    
    if importances is not None:
        original_feature_importances = importances.copy()
  
    base_out_dir = os.path.join(args.base_dir, 'rf', 'models', 'oof', args.model_name)
    exclude_fold = {'01':'2', '02':'1', '12':'0'}[args.original_train_on]
    held_out = 'fold_'+exclude_fold
    for dirname in os.listdir(args.dataset_dir):
            #print(dirname)
            if held_out in str(dirname):
                held_path = os.path.join(args.dataset_dir, dirname)
    metrics = {
        'accuracy': {}
    }
    for sp in species_list:
        # load stacker
        stacker = joblib.load(os.path.join(base_out_dir, 'stacker', f"{sp}_stacker.joblib"))
        # build base predictions
        base_preds = []
        for ft in ['hits','dnabert']:

            if importances is not None:
                feature_importances = {}
                if ft == 'hits':
                    feature_importances[sp] = [f for f in original_feature_importances[sp] if '_hit_count' in f]
                else:
                    feature_importances[sp] = [f for f in original_feature_importances[sp] if '_pred_resistant' in f]
            else:
                feature_importances=None

            
            model = joblib.load(os.path.join(base_out_dir, ft, f"exclude_{held_out}", f"{sp}_{args.model_type}_model.joblib"))
            df = pd.read_csv(os.path.join(held_path, args.dnabert_grouping, 'train', sp, f"{sp}_full_rf_dataset.csv"))
            args.feature_type=ft
            df = preprocess_df(df, sp, args, feature_importances)
            X_inf = df.drop('ground_truth_phenotype', axis=1)
            
            base_preds.append(model.predict_proba(X_inf)[:,1])
        X_meta = np.column_stack(base_preds)
        y_true = df['ground_truth_phenotype'].values
        metrics['accuracy'][sp] = accuracy_score(y_true, stacker.predict(X_meta))
    print(f'\nOOF stacker accuracy on {held_out}:')
    for sp,a in metrics['accuracy'].items():
        print(f"{sp:25s}: {a:.3f}")
    print(f"mean: {np.mean(list(metrics['accuracy'].values())):.3f}")


    accuracy = np.mean(list(metrics['accuracy'].values()))
    recall = None #np.mean(list(metrics['recall'].values()))
    precision = None #np.mean(list(metrics['precision'].values()))
    f1 = None #np.mean(list(metrics['f1'].values()))
    aucroc = None #np.mean(list(metrics['aucroc'].values()))
    neisseria_gonorrhoeae_acc = metrics['accuracy']['neisseria_gonorrhoeae']
    staphylococcus_aureus_acc = metrics['accuracy']['staphylococcus_aureus']
    streptococcus_pneumoniae_acc = metrics['accuracy']['streptococcus_pneumoniae']
    salmonella_enterica_acc = metrics['accuracy']['salmonella_enterica']
    klebsiella_pneumoniae_acc = metrics['accuracy']['klebsiella_pneumoniae']
    escherichia_coli_acc = metrics['accuracy']['escherichia_coli']
    pseudomonas_aeruginosa_acc = metrics['accuracy']['pseudomonas_aeruginosa']
    acinetobacter_baumannii_acc = metrics['accuracy']['acinetobacter_baumannii']
    campylobacter_jejuni_acc = metrics['accuracy']['campylobacter_jejuni']
    TET_acc = np.mean([metrics['accuracy'][species] for species in antibiotic_to_species['TET']])
    GEN_acc = np.mean([metrics['accuracy'][species] for species in antibiotic_to_species['GEN']])
    ERY_acc = np.mean([metrics['accuracy'][species] for species in antibiotic_to_species['ERY']])
    CAZ_acc = np.mean([metrics['accuracy'][species] for species in antibiotic_to_species['CAZ']])

    df = pd.read_csv('eval_results/rf_models.csv')
    df = df._append({'accuracy': accuracy, 'model_name': args.model_name, 'model_type': args.model_type, 'train_on': args.train_on, 'feature_type': args.feature_type, 'min_samples_leaf': args.min_samples_leaf, \
    'max_depth': args.max_depth, 'top_n_mi_score': args.top_n_mi_score, 'recall': recall, 'precision': precision, 'f1': f1, 'aucroc': aucroc, 'neisseria_gonorrhoeae_acc': neisseria_gonorrhoeae_acc, \
    'staphylococcus_aureus_acc': staphylococcus_aureus_acc, 'streptococcus_pneumoniae_acc': streptococcus_pneumoniae_acc, 'salmonella_enterica_acc': salmonella_enterica_acc, 'klebsiella_pneumoniae_acc': klebsiella_pneumoniae_acc,\
    'escherichia_coli_acc': escherichia_coli_acc, 'pseudomonas_aeruginosa_acc': pseudomonas_aeruginosa_acc, 'acinetobacter_baumannii_acc': acinetobacter_baumannii_acc, 'campylobacter_jejuni_acc': campylobacter_jejuni_acc, 'TET_acc': TET_acc,\
    'GEN_acc': GEN_acc, 'ERY_acc': ERY_acc, 'CAZ_acc': CAZ_acc}, ignore_index=True)
    df.to_csv('eval_results/rf_models.csv', index=False)

    return metrics
    

def train(args, importances=None):
    #print(f"Training {args.model_type}")

    if args.grouping == 'per_species':
        for species in species_list:
            if args.train_on in ['01','02','12']:
                # map which fold to hold out
                exclude_fold = {'01':'2', '02':'1', '12':'0'}[args.train_on]
                dfs = []
                for dirname in os.listdir(args.dataset_dir):
                    fold=dirname.split('_')[-1]
                    if fold == exclude_fold:
                        #print(f"Skipping fold {dirname} in training")
                        continue
                    dfs.append(pd.read_csv(os.path.join(args.dataset_dir, dirname, args.dnabert_grouping, 'train', species, f"{species}_full_rf_dataset.csv")))
                df = pd.concat(dfs)
                
            elif args.train_on=='all': # if all is selcted, should pass path to dir containing per-species dirs
                dfs = []
                for dirname in os.listdir(args.dataset_dir):
                    dfs.append(pd.read_csv(os.path.join(args.dataset_dir, dirname, args.dnabert_grouping, 'train', species, f"{species}_full_rf_dataset.csv")))
                df = pd.concat(dfs)
            else:
                raise ValueError(f"Invalid train_on value: {args.train_on}")

            df = preprocess_df(df, species, args, importances)
            X = df.drop('ground_truth_phenotype', axis=1)
            y = df['ground_truth_phenotype']
            
            #X = filter_top_n_mi(X=X, y=y, species=species, models_dir=args.out_dir, top_n_mi_score=args.top_n_mi_score)

            #print(args.feature_type)
            #print(X.columns)
            assert len(X) == len(y)


            # Initialize model based on requested type
            if args.model_type == 'xgb':
                from xgboost import XGBClassifier
                if args.tune_hyperparams:
                    model =  XGBClassifier(
                            n_estimators=args.n_estimators,
                            max_depth=args.max_depth,
                            learning_rate=args.learning_rate,
                            subsample=args.subsample,
                            colsample_bytree=args.colsample_bytree,
                            min_child_weight=args.min_child_weight,
                            reg_lambda=args.reg_lambda,
                            reg_alpha=args.reg_alpha,
                            tree_method=args.tree_method,
                            booster=args.booster,
                            objective='binary:logistic',
                            eval_metric='logloss',
                            use_label_encoder=False,
                            random_state=42
                        )
                elif args.load_hyperparams is not None:
                    print('loading hyperparams')
                    model =  XGBClassifier(
                            n_estimators=hyperparam_args['n_estimators'],
                            max_depth=hyperparam_args['max_depth'],
                            learning_rate=hyperparam_args['learning_rate'],
                            subsample=hyperparam_args['subsample'],
                            colsample_bytree=hyperparam_args['colsample_bytree'],
                            min_child_weight=hyperparam_args['min_child_weight'],
                            reg_lambda=hyperparam_args['reg_lambda'],
                            reg_alpha=hyperparam_args['reg_alpha'],
                            tree_method=hyperparam_args['tree_method'],
                            booster=hyperparam_args['booster'],
                            objective='binary:logistic',
                            eval_metric='logloss',
                            use_label_encoder=False,
                            random_state=42
                        )
                else:
                    model=XGBClassifier(random_state=42)
            elif args.model_type=='rf':  # Random Forest

                if args.tune_hyperparams:
                    model = RandomForestClassifier(
                        n_estimators=args.n_estimators,
                        max_depth=args.max_depth, 
                        min_samples_split=args.min_samples_split,
                        random_state=42,
                        max_features=args.max_features,
                        bootstrap=args.bootstrap,
                        class_weight=args.class_weight,
                        criterion=args.criterion,
                        min_samples_leaf=args.min_samples_leaf
                    )
                else:
                    model = RandomForestClassifier(random_state=42)
    
            elif args.model_type=='lr':
                from sklearn.linear_model import LogisticRegression
                model = LogisticRegression(penalty='l2', random_state=42, max_iter=1000)
            elif args.model_type == 'cb':
                from catboost import CatBoostClassifier
                if args.tune_hyperparams:
                    model = CatBoostClassifier(
                        iterations=args.iterations,
                        learning_rate=args.learning_rate,
                        depth=args.depth,
                        l2_leaf_reg=args.l2_leaf_reg,
                        subsample=args.subsample,
                        colsample_bylevel=0.8,
                        bootstrap_type=args.bootstrap_type,
                        loss_function='Logloss',
                        grow_policy=args.grow_policy,
                        random_strength=args.random_strength,
                        random_seed=42,
                        verbose=100
                    )
                elif args.load_hyperparams is not None:
                    model = CatBoostClassifier(
                        iterations=hyperparam_args['iterations'],
                        learning_rate=hyperparam_args['learning_rate'],
                        depth=hyperparam_args['depth'],
                        l2_leaf_reg=hyperparam_args['l2_leaf_reg'],
                        subsample=hyperparam_args['subsample'],
                        colsample_bylevel=0.8,
                        bootstrap_type=hyperparam_args['bootstrap_type'],
                        loss_function='Logloss',
                        grow_policy=hyperparam_args['grow_policy'],
                        random_strength=hyperparam_args['random_strength'],
                        random_seed=42,
                        verbose=100
                    )
            elif args.model_type=='nn':
                from models.nn.nn_model import MultiQueryNN, train_nn, predict_nn
                device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
                num_query_ids = len(X.columns) // 7
                model = MultiQueryNN(num_query_ids=num_query_ids)
                model.to(device)
                X = torch.tensor(X.to_numpy(dtype=np.float32))
                y = torch.tensor(y.values, dtype=torch.float32).view(-1, 1)
                model = train_nn(model, X, y, device, lr=1e-4, batch_size=32, epochs=25)
                torch.save(model.state_dict(), os.path.join(args.out_dir, f"{species}_nn_model.pt"))
                



            #print(feature_importances)
      
            if args.model_type != 'nn':
                model.fit(X, y)

                # save model (keep same filename pattern so feature_plot works)
    
                model_path = os.path.join(args.out_dir, f"{species}_{args.model_type}_model.joblib")
                joblib.dump(model, model_path)

    else:
        raise NotImplementedError(f"Grouping {args.grouping} not implemented")


def eval(args, importances=None):
    """Evaluate RF models on FOLD 2"""


    metrics = {
    'accuracy': {},
        'precision': {},
        'recall': {},
        'f1': {},
        'aucroc': {},
        }

    exclude_fold = {'01':'2', '02':'1', '12':'0'}[args.train_on]
    eval_on = 'fold_'+exclude_fold

    pred_dfs = []

    for species in species_list:
        if args.model_type != 'nn':
            model_path = os.path.join(args.out_dir, f"{species}_{args.model_type}_model.joblib")
            model = joblib.load(model_path)
        else:
            pass
            

        for fold in os.listdir(args.dataset_dir):
            if fold.endswith(eval_on):
                test_df = pd.read_csv(os.path.join(args.dataset_dir, fold, args.dnabert_grouping, 'train', species, f"{species}_full_rf_dataset.csv"))
                break
        print(f'Evaluating on dataset: {args.dataset_dir}/{fold}/{args.dnabert_grouping}/train/{species}/{species}_full_rf_dataset.csv')
        accessions = test_df['accession'].values
        test_df = preprocess_df(test_df, species, args, importances)
        X = test_df.drop('ground_truth_phenotype', axis=1)
        
        if args.model_type != 'nn':
            preds = model.predict(X)
        else:
            from models.nn.nn_model import MultiQueryNN, predict_nn
            device = torch.device('cpu')  # or 'cuda' if available
            model_path = os.path.join(args.out_dir, f"{species}_nn_model.pt")

            # reconstruct model architecture
            num_query_ids = len([c for c in X.columns if c.endswith('_hit_count')])
            model = MultiQueryNN(num_query_ids=num_query_ids)
            model.load_state_dict(torch.load(model_path, map_location=device))
            model.to(device)
            model.eval()
            X_tensor = torch.tensor(X.to_numpy(dtype=np.float32))
            preds = predict_nn(model, X_tensor, device)

        truth = test_df['ground_truth_phenotype'].values
        assert len(preds) == len(truth)
        metrics['accuracy'][species] = accuracy_score(truth, preds)
        metrics['precision'][species] = precision_score(truth, preds)
        metrics['recall'][species] = recall_score(truth, preds)
        metrics['f1'][species] = f1_score(truth, preds)
        metrics['aucroc'][species] = roc_auc_score(truth, preds)

        pred_df = pd.DataFrame({'accession': accessions, 'pred': preds, 'true': truth})
        pred_dfs.append(pred_df)

    
    # report metrics
    #for metric_name, metric_dict in metrics.items():
        #print(f"Mean {metric_name}: {np.mean(list(metric_dict.values()))}")
        #print()
        #for species in species_list:
        #print(f"{species}: {metric_dict[species]}")
        #print()

    # save metrics to json
    if not args.tune_hyperparams:
        results_dir = os.path.join('eval_results', args.model_name)
        os.makedirs(results_dir, exist_ok=True)
        with open(os.path.join(results_dir, 'eval_results.json'), 'w') as f:
            json.dump(metrics, f)

        # save args to results dir
        with open(os.path.join(results_dir, 'args.json'), 'w') as f:
            json.dump(args.__dict__, f)



    accuracy = np.mean(list(metrics['accuracy'].values()))
    recall = np.mean(list(metrics['recall'].values()))
    precision = np.mean(list(metrics['precision'].values()))
    f1 = np.mean(list(metrics['f1'].values()))
    aucroc = np.mean(list(metrics['aucroc'].values()))
    neisseria_gonorrhoeae_acc = metrics['accuracy']['neisseria_gonorrhoeae']
    staphylococcus_aureus_acc = metrics['accuracy']['staphylococcus_aureus']
    streptococcus_pneumoniae_acc = metrics['accuracy']['streptococcus_pneumoniae']
    salmonella_enterica_acc = metrics['accuracy']['salmonella_enterica']
    klebsiella_pneumoniae_acc = metrics['accuracy']['klebsiella_pneumoniae']
    escherichia_coli_acc = metrics['accuracy']['escherichia_coli']
    pseudomonas_aeruginosa_acc = metrics['accuracy']['pseudomonas_aeruginosa']
    acinetobacter_baumannii_acc = metrics['accuracy']['acinetobacter_baumannii']
    campylobacter_jejuni_acc = metrics['accuracy']['campylobacter_jejuni']
    TET_acc = np.mean([metrics['accuracy'][species] for species in antibiotic_to_species['TET']])
    GEN_acc = np.mean([metrics['accuracy'][species] for species in antibiotic_to_species['GEN']])
    ERY_acc = np.mean([metrics['accuracy'][species] for species in antibiotic_to_species['ERY']])
    CAZ_acc = np.mean([metrics['accuracy'][species] for species in antibiotic_to_species['CAZ']])

    try:
        df = pd.read_csv('eval_results/rf_models.csv')
        df = df._append({'accuracy': accuracy, 'model_name': args.model_name, 'model_type': args.model_type, 'train_on': args.train_on, 'feature_type': args.feature_type, 'min_samples_leaf': args.min_samples_leaf, \
        'max_depth': args.max_depth, 'top_n_mi_score': args.top_n_mi_score, 'recall': recall, 'precision': precision, 'f1': f1, 'aucroc': aucroc, 'neisseria_gonorrhoeae_acc': neisseria_gonorrhoeae_acc, \
        'staphylococcus_aureus_acc': staphylococcus_aureus_acc, 'streptococcus_pneumoniae_acc': streptococcus_pneumoniae_acc, 'salmonella_enterica_acc': salmonella_enterica_acc, 'klebsiella_pneumoniae_acc': klebsiella_pneumoniae_acc,\
        'escherichia_coli_acc': escherichia_coli_acc, 'pseudomonas_aeruginosa_acc': pseudomonas_aeruginosa_acc, 'acinetobacter_baumannii_acc': acinetobacter_baumannii_acc, 'campylobacter_jejuni_acc': campylobacter_jejuni_acc, 'TET_acc': TET_acc,\
        'GEN_acc': GEN_acc, 'ERY_acc': ERY_acc, 'CAZ_acc': CAZ_acc}, ignore_index=True)
        df.to_csv('eval_results/rf_models.csv', index=False)
    except Error as e:
        print(f'Could not write to rf_models.csv: {e}')

    #save csv of accession, pred, true
    pred_df = pd.concat(pred_dfs)
    os.makedirs(f'eval_results/{args.model_name}', exist_ok=True)
    pred_df.to_csv(f'eval_results/{args.model_name}/{eval_on}_preds.csv', index=False)
        
    return metrics


def tune_hyperparams(args, num_iterations=100):
    """iterate through tunable hyperparams to get best model based on args.tune_metric
    writes all models tested to eval_results/rf_models.csv"""

    import random

    #cb
    if args.model_type == 'cb':
        param_grid = {
            "iterations": [300, 500],
            "learning_rate": [0.05, 0.1],
            "depth": [4, 6],
            "l2_leaf_reg": [5, 9],
            "subsample": [0.8, 1.0],
            "bootstrap_type": ["Bernoulli"],
            "grow_policy": ["SymmetricTree"],
            "random_strength": [1],
        }

    #xgb
    elif args.model_type == 'xgb':
        param_grid = {
            "n_estimators": [100, 300],
            "learning_rate": [0.05, 0.1],
            "max_depth": [4, 6, 8],
            "subsample": [0.7, 1.0],
            "colsample_bytree": [0.6, 0.8, 1.0],
            "min_child_weight": [1, 3],
            "reg_lambda": [1, 5],
            "reg_alpha": [0, 1],
            "tree_method": ["hist"],
            "booster": ["gbtree"],
        }

    #rf
    elif args.model_type == 'rf':
        param_grid = {
            "n_estimators": [100, 200, 400],
            "max_depth": [None, 10, 20],
            "min_samples_split": [2, 5],
            "min_samples_leaf": [1, 2, 5, 10],
            "max_features": ["sqrt", "log2", 0.5],    # limits dominance of high-cardinality features
            "bootstrap": [True],
            "class_weight": ["balanced"],              # safe even if slightly imbalanced in practice
            "criterion": ["gini", "entropy"],
        }
    else:
        raise NotImplementedError(f'No param grid for model type {args.model_type}')



    print(f"Tuning hyperparams with parameters: {param_grid}...")

    if not os.path.exists('eval_results/rf_models.csv'):
        with open('eval_results/rf_models.csv', 'w') as f:
            df = pd.DataFrame(columns=['accuracy', 'model_name', 'train_on', 'feature_type', 'min_samples_leaf', \
            'max_depth', 'top_n_mi_score', 'recall', 'precision', 'f1', 'aucroc', 'neisseria_gonorrhoeae_acc', \
            'staphylococcus_aureus_acc', 'streptococcus_pneumoniae_acc', 'salmonella_enterica_acc', 'klebsiella_pneumoniae_acc', \
            'escherichia_coli_acc', 'pseudomonas_aeruginosa_acc', 'acinetobacter_baumannii_acc', 'campylobacter_jejuni_acc', \
            'TET_acc', 'GEN_acc', 'ERY_acc', 'CAZ_acc'])
            df.to_csv('eval_results/rf_models.csv', index=False)

    results_dir = f'eval_results/{args.model_name}'
    original_model_name = args.model_name
    os.makedirs(results_dir, exist_ok=True)
    name_to_acc = {}
    name_to_params = {}

    for i in tqdm(range(num_iterations)):
        sampled_params = {k: random.choice(v) for k, v in param_grid.items()}
        for k, v in sampled_params.items():
            setattr(args, k, v)
        
        args.model_name = original_model_name + '_' + str(i)
        
        train(args)
        metrics = eval(args)

        #save args and accuracy
        accuracy = np.mean(list(metrics['accuracy'].values()))

        name_to_acc.update({args.model_name: accuracy})
        name_to_params.update({args.model_name: sampled_params})

        args.accuracy = accuracy
        with open(results_dir+f'/{args.model_name}.json', 'w') as f:
            json.dump(args.__dict__, f)

    #OOF CV on best params:
    best_model = max(name_to_acc, key=name_to_acc.get)
    best_params = name_to_params[best_model]
    for k, v in best_params.items():
        setattr(args, k, v)

    args.model_name = original_model_name + '_BEST'
    for train_on in ['01', '02', '12']:
        args.train_on = train_on
        print(f"Training on {train_on}")
        train(args)
        metrics = eval(args)
        accuracy = np.mean(list(metrics['accuracy'].values()))
        args.accuracy = accuracy
        with open(results_dir+f'/{args.model_name}.json', 'w') as f:
            json.dump(args.__dict__, f)

    





                    
            
            
        


    

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset_dir', type=str, help='Path to directory containing datasets formatted by dnabert/inference/inference.py', default='../dnabert/inference/outputs/rf_datasets/full_model_species_only_v2/per_species/train')
    parser.add_argument('--grouping', type=str, choices=['full', 'per_antibiotic', 'per_species'], help='Grouping for models (per_species=9 models, per_antibiotic=4 models, full=1 model)', default='per_species')
    parser.add_argument('--dnabert_grouping', type=str, choices=['full', 'per_antibiotic', 'per_species'], help='Grouping for DNABERT models (per_species=9 models, per_antibiotic=4 models, full=1 model)', default='full')
    parser.add_argument('--model_name', type=str, help='Name of DNABERT model used and info about this run', default=None)
    parser.add_argument('--out_dir', type=str, help='Directory to save models', default=None)
    parser.add_argument('--train_on', type=str, choices=['01', '02', '12', 'all'], help='Which FOLDs to train on', default='all')
    parser.add_argument('--feature_type', type=str, choices=['dnabert', 'hits', 'both'], help='Whether to use DNABERT features, hits, or both', default='both')
    parser.add_argument('--eval', action='store_true', help='Whether to evaluate models, this will eval on fold 3; train_on folds 01 should be selected', default=False)
    parser.add_argument('--base_dir', default='/gpfs/scratch/jvaska/CAMDA_AMR/AMR_v2')
    parser.add_argument('--model_type', type=str, choices=['rf', 'xgb', 'lr', 'cb', 'nn'], default='rf', help='Which model type to train (rf or xgb)')
    parser.add_argument('--interleave', action='store_true', help='If true, --feature_plot must point to HITS-only models. The routine constructs an interleaved ranking where each hit feature is paired with its corresponding DNABERT feature (<sig_seq_id>_pred_resistant). This ranking is then used for ft="dnabert" (DNABERT-only names), ft="hits" (hits-only), and ft="both" (hit, dnabert, hit, dnabert …). %% of features is computed w.r.t. hits count.')
    parser.add_argument('--skip_accs', type=str, help='Path to dir containing files with accessions to skip per species', default=None)
    parser.add_argument('--flip_phenotype', type=str, help='will flip phenotype for accessions in these species lists', default='/gpfs/scratch/jvaska/CAMDA_AMR/AMR_v2/data_analysis/mismatches') #this was causing poor accuracy on new pipeline, so we should ALWAYS be flipping phenotype of these accs
    parser.add_argument('--top_15pct_features', type=str, help='Path to dir containing files with top 15pct features per species. If specified, will remove ONLY dnabert features without query_ids specified in those files', default=None)

    parser.add_argument('--feature_plot', type=str, help='Whether to plot accuracy vs num features, if path to models for features is passed, will plot accuracy vs num features for each model', default=None)
    parser.add_argument('--oof_stack', action='store_true', help='If set, perform 3-fold out-of-fold stacking: train base hits and DNABERT models on complementary folds and a 2-feature logistic meta learner.')
    parser.add_argument('--tune_hyperparams', action='store_true', help='Whether to tune hyperparameters', default=False)
    parser.add_argument('--tune_metric', type=str, choices=['accuracy', 'precision', 'recall', 'f1', 'aucroc'], help='Metric to tune hyperparameters on', default='accuracy')
    #tunable hyperparams - defaults are best parameters from tuning
    parser.add_argument('--n_estimators', type=int, help='Number of trees in the random forest', default=None) #default=250)
    parser.add_argument('--max_depth', type=int, help='Maximum depth of the trees', default=None) #default=40)
    parser.add_argument('--min_samples_leaf', type=int, help='Minimum number of samples required to be at a leaf node', default=1)
    parser.add_argument('--top_n_mi_score', type=int, help='Number of features to keep based on mutual information score', default=None) #, default=300
    parser.add_argument('--scaler', choices=['standard', None], default=None)
    parser.add_argument('--load_hyperparams', type=str, help='Path to json containing arguments of best hyperparameters', default=None)

    
    args = parser.parse_args()
    args.original_train_on = args.train_on
    if args.load_hyperparams is not None:
        global hyperparam_args
        with open(args.load_hyperparams, 'r') as f:
            hyperparam_args = json.load(f)

    if args.out_dir is None:
        if args.feature_plot is not None:
            args.out_dir = os.path.join(args.base_dir, 'rf', 'models', args.model_type, args.grouping, args.model_name, 'feature_plot_temp')
        else:
            print(args)
            args.out_dir = os.path.join(args.base_dir, 'rf', 'models', args.model_type, args.grouping, args.model_name)
        if args.oof_stack:
            # store under models/oof/model_name
            args.out_dir = os.path.join(args.base_dir, 'rf', 'models', 'oof', args.model_name)

    os.makedirs(args.out_dir, exist_ok=True)

    # ----- dispatch for OOF stacking -----
    if args.oof_stack and args.feature_plot is None:
        if args.eval:
            for train_on in ['01', '02', '12']:
                args.original_train_on = train_on
                print(f'OOF train on {args.train_on}')
                oof_train(args)
                eval_oof(args)
        else:
            oof_train(args)
        return

    if args.tune_hyperparams:
        tune_hyperparams(args)
    else:
        if args.feature_plot is not None:
            feature_plot(args)
        elif args.eval:
            for train_on in ['01', '02', '12']:
                args.train_on = train_on
                print(f"Training on {train_on}")
                train(args)
                eval(args)
        else:
            print('Training...')
            train(args)
        


if __name__ == '__main__':
    main()
